[workspace]
resolver = "2"
members = [
    "shared/nexus-abi",
    "shared/nexus-font",
    "shared/nexus-i18n",
    "shared/nexus-net",
    "boot/nexus-boot",
    "kernel/nexus-mm",
    "kernel/nexus-kernel",
    "user/nexus-user",
    "user/nexus-ui",
    "user/nexus-init",
    "user/nexus-hello",
    "user/nexus-compositor",
    "user/nexus-client",
    "user/nexus-shell",
    "user/nexus-idle",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["The NexusOS Project"]

[profile.dev]
panic = "abort"
opt-level = 1
debug = true
overflow-checks = true

[profile.release]
panic = "abort"
opt-level = 2
debug = true
lto = false
codegen-units = 1
overflow-checks = true
