[workspace]
resolver = "2"
members = [
    "shared/nexus-ai",
    "user/nexus-ai",
    "shared/nexus-abi",
    "shared/nexus-font",
    "shared/nexus-i18n",
    "shared/nexus-json",
    "shared/nexus-machine",
    "shared/nexus-inflate",
    "shared/nexus-image",
    "shared/nexus-index",
    "shared/nexus-net",
    "shared/nexus-time",
    "shared/nexus-config",
    "shared/nexus-update",
    "shared/nexus-netclient",
    "shared/nexus-shellwords",
    "shared/nexus-look",
    "shared/nexus-ime",
    "shared/nexus-dns",
    "shared/nexus-http",
    "shared/nexus-html",
    "shared/nexus-crypto",
    "shared/nexus-pkg",
    "tools/nexus-pack",
    "tools/nexus-collab",
    "tools/nexus-linux-example",
    "boot/nexus-boot",
    "kernel/nexus-mm",
    "kernel/nexus-kernel",
    "user/nexus-user",
    "user/nexus-ui",
    "user/nexus-window",
    "user/nexus-init",
    "user/nexus-hello",
    "user/nexus-compositor",
    "user/nexus-client",
    "user/nexus-shell",
    "user/nexus-install",
    "user/nexus-find",
    "user/nexus-update",
    "user/nexus-browser",
    "user/nexus-term",
    "user/nexus-wall",
    "user/nexus-settings",
    "user/nexus-store",
    "user/nexus-view",
    "user/nexus-launch",
    "user/nexus-assist",
    "user/nexus-setup",
    "user/nexus-idle",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["The NexusOS Project"]

[profile.dev]
panic = "abort"
opt-level = 1
debug = true
overflow-checks = true

[profile.release]
panic = "abort"
opt-level = 2
debug = true
lto = false
codegen-units = 1
overflow-checks = true
