[package]
name = "nexus-term"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "A terminal window, and a shell to type into it."

[[bin]]
name = "nexus-term"
path = "src/main.rs"
test = false

[dependencies]
nexus-api = { path = "../nexus-api" }
nexus-user = { path = "../nexus-user" }
nexus-ui = { path = "../nexus-ui" }
nexus-i18n = { path = "../../shared/nexus-i18n" }
nexus-time = { path = "../../shared/nexus-time" }
nexus-shellwords = { path = "../../shared/nexus-shellwords" }
nexus-config = { path = "../../shared/nexus-config" }
nexus-look = { path = "../../shared/nexus-look" }
nexus-ime = { path = "../../shared/nexus-ime" }
nexus-machine = { path = "../../shared/nexus-machine" }
nexus-netclient = { path = "../../shared/nexus-netclient" }
nexus-dns = { path = "../../shared/nexus-dns" }
